
[Interface]
Address = :CLIENT_IP:/32, :CLIENT_IP6:/128
PrivateKey = :CLIENT_KEY:
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = :SERVER_PUB_KEY:
Endpoint = :SERVER_ENDPOINT:
# Route only VPN traffic through VPN
# AllowedIPs = :SERVER_NET:, :SERVER_NET6:
# Route all traffic through VPN
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
