
[Interface]
PrivateKey = :SERVER_PRIV_KEY:
Address = :SERVER_IP:/:SERVER_PREFIX:, :SERVER_IP6:/:SERVER_PREFIX6:
ListenPort = :SERVER_PORT:
SaveConfig = false

# PostUp = iptables -t nat -A PREROUTING -i %i -p udp --dport 53 -j DNAT --to-destination :SERVER_IP::53
# PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 53 -j DNAT --to-destination :SERVER_IP::53

PostUp = iptables -A FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PostUp = iptables -A FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
PostUp = ip6tables -A FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PostUp = ip6tables -A FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

PostUp = iptables -t nat -A POSTROUTING -s :SERVER_NET: -o :SERVER_IF: -j MASQUERADE
PostUp = ip6tables -t nat -A POSTROUTING -s :SERVER_NET6: -o :SERVER_IF: -j MASQUERADE

# PreDown = iptables -t nat -D PREROUTING -i %i -p udp --dport 53 -j DNAT --to-destination :SERVER_IP::53
# PreDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 53 -j DNAT --to-destination :SERVER_IP::53

PreDown = iptables -D FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PreDown = iptables -D FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
PreDown = ip6tables -D FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PreDown = ip6tables -D FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

PreDown = iptables -t nat -D POSTROUTING -s :SERVER_NET: -o :SERVER_IF: -j MASQUERADE
PreDown = ip6tables -t nat -D POSTROUTING -s :SERVER_NET6: -o :SERVER_IF: -j MASQUERADE
